title: <p align="center">Aniket Saindankar</p>
logo: /assets/img/resume_photo.png

description: |
  <div style="text-align: center;">
    <p>
      <a href="/assets/aniket-saindankar-data-analyst (3)" target="_blank"
         style="display:inline-block; padding:8px 16px; background-color:#0073b1; 
                color:white; text-decoration:none; border-radius:6px; font-weight:bold;">
        📄 Download Resume
      </a>
    </p>
    <p>
      <a href="https://www.linkedin.com/in/aniket-saindankar-03a71b1a7/">🔗 LinkedIn</a> |
      <a href="https://github.com/aniket25-jpg">💻 GitHub</a> |
      <a href="mailto:saindankaraniket@gmail.com">📧 Email</a>
    </p>
  </div>

theme: jekyll-theme-minimal
